version: "3.5"

services:
  app:
    container_name: swoole-test
    build:
      context: .
      args:
        timezone: Europe/Paris
        uid: 1000
    environment:
      APP_ENV: dev
      HOST: 0.0.0.0
      PORT: 9501
      MONOLOG_MAIN_STREAM_PATH: php://stdout
      MONOLOG_DEPRECATIONS_STREAM_PATH: php://sterr
      SWOOLE_LOG_STREAM_PATH: /proc/self/fd/1
      DATABASE_URL: "mysql://root:dev@db:3306/test?serverVersion=8.0"
    ports:
      - "9501:9501"
    volumes:
      - ./src:/usr/src/app
  db:
    image: mysql:8
    container_name: swoole-test-db
    environment:
      - MYSQL_ROOT_PASSWORD=dev
    ports:
      - "3306:3306"
      - "33060:22060"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/custom.cnf
  redis:
    image: redis:6.2
    container_name: swoole-test-redis
    ports:
      - "6379:6379"