CREATE TABLE `test` (
                        `int` int NOT NULL AUTO_INCREMENT,
                        `varchar` varchar(45) DEFAULT NULL,
                        `datetime` datetime DEFAULT NULL,
                        `date` date DEFAULT NULL,
                        `json` json DEFAULT NULL,
                        `decimal` decimal(12,3) DEFAULT NULL,
                        `bigint` bigint DEFAULT NULL,
                        `double` double DEFAULT NULL,
                        `float` float DEFAULT NULL,
                        `mediumint` mediumint DEFAULT NULL,
                        `real` double DEFAULT NULL,
                        `smallint` smallint DEFAULT NULL,
                        `tinyint` tinyint DEFAULT NULL,
                        `char` char(12) DEFAULT NULL,
                        `nchar` char(5) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
                        `nvarchar` varchar(12) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
                        `longtext` longtext,
                        `mediumtext` mediumtext,
                        `tinytext` tinytext,
                        `testcol` tinyint DEFAULT NULL,
                        `testcol1` text,
                        `boolean` int DEFAULT NULL,
                        PRIMARY KEY (`int`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
