sebk_small_orm:
  connections:
    default:
      type: mysql
      host: db
      database: test
      encoding: utf8
      user:     root
      password: dev

  generator:
    folders:
      App\TestBundle: src/TestBundle
      App\RedisBundle: src/RedisBundle
      App\Try: src/Try
    selectors:
      test:
        dao_namespace: App\TestBundle\Dao
        model_namespace: App\TestBundle\Model
      redis:
        dao_namespace: App\RedisBundle\Dao
        model_namespace: App\RedisBundle\Model
      try:
        dao_namespace: App\Try\Dao
        model_namespace: App\Try\Model